# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0  # Or latest at time
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.11.0  # Python code formatter
    hooks:
      - id: black
        language_version: python3

default_stages: [pre-commit]
