name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    uses: ./.github/workflows/reusable/jekyll-build.yml
    with:
      branch: "main"
