name: Jekyll docker site CI

on:
  push:
    branches: [ "base" ]
  pull_request:
    branches: [ "base" ]

jobs:
  build:
    uses: ./.github/workflows/reusable/jekyll-build.yml
    with:
      branch: "base"
